<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>TouchPadRaw</AssemblyName>
    <RootNamespace>TouchPadRaw</RootNamespace>
    <Version>1.0.0</Version>
  </PropertyGroup>

</Project>
